// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TinyShopping.Core.Net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Item
    {
        /// <summary>
        /// Initializes a new instance of the Item class.
        /// </summary>
        public Item()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Item class.
        /// </summary>
        public Item(int? id = default(int?), System.DateTime? added = default(System.DateTime?), System.DateTime? done = default(System.DateTime?), string name = default(string), bool? completed = default(bool?), int? listId = default(int?), double? lat = default(double?), double? lng = default(double?))
        {
            Id = id;
            Added = added;
            Done = done;
            Name = name;
            Completed = completed;
            ListId = listId;
            Lat = lat;
            Lng = lng;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "added")]
        public System.DateTime? Added { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "done")]
        public System.DateTime? Done { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "completed")]
        public bool? Completed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "listId")]
        public int? ListId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lat")]
        public double? Lat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lng")]
        public double? Lng { get; set; }

    }
}
